### ISSUE TITLE
TTS Community Github Org

### ISSUE THREAD

**Issue by Benjamin-Dobell** [matanlurey/tts-save-format#5]
You've got some seriously impressive TTS projects here!

There's a small community of us tackling similar tooling issues over at https://github.com/tts-community/ and (fairly informally) coordinating on Discord https://discord.gg/qpQPZaq.

For example, a few things I've been working on are [debugging support](https://github.com/tts-community/moonsharp), a [statically typed Lua IDE](https://github.com/EmmyLua/IntelliJ-EmmyLua/pulls), corresponding [TTS Lua API types](https://github.com/Benjamin-Dobell/tts-types), [Lua bundling (`require` support)](https://github.com/Benjamin-Dobell/luabundle) and a headless "build" of TTS to support dedicated servers and matchmaking (presently only some [Docker bits](https://github.com/Benjamin-Dobell/docker-tts) are public).

Others are working on other tooling very similar to your own i.e. deconstructing TTS saves, VSCode extensions, external object editor/browsers etc.

No doubt you're very busy and this is just low priority hobby stuff. However, even if you don't have time to drop by Discord, any PRs you want to submit to https://github.com/tts-community/tts-community.github.io linking out to your stuff would also be very much appreciated.

**Comment by PolyphonyRequiem** [comment]
Shoutout to the discord though, it's about 20 of us, and it's relatively active.
